"""設定ファイルのサンプル
このファイルを config.py にコピーして使用してください。
"""

import os
from pathlib import Path

# プロジェクトのルートディレクトリ
ROOT_DIR = Path(__file__).parent.parent

# テンプレートディレクトリ
TEMPLATE_DIR = ROOT_DIR / 'templates'

# CSSディレクトリ
CSS_DIR = ROOT_DIR / 'css'

# PDF設定
PDF_CONFIG = {
    'CREDIT_STRING': "Generated by Chrome PDF Extension",  # クレジット文字列
    'FOOTER_FONT_SIZE': 8,  # フッターのフォントサイズ
    'FOOTER_MARGIN': 30,    # フッターの下端からのマージン
    'FOOTER_FONT': "Helvetica"  # フッターのフォント
}

# Markdown拡張機能の設定
MARKDOWN_EXTENSIONS = [
    'toc',
    'tables', 
    'fenced_code',
    'attr_list'
]

# シンタックスハイライトの設定
CODEHILITE_CONFIG = {
    'use_pygments': True,
    'noclasses': True,
    'pygments_style': 'default',
    'linenums': False,
    'guess_lang': True
}

def load_template_file(file_path):
    """テンプレートファイルを読み込む"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Warning: Template file not found: {file_path}")
        return ""

def load_css_file(file_path):
    """CSSファイルを読み込む"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Warning: CSS file not found: {file_path}")
        return ""

# デフォルトのテンプレートファイルパス
DEFAULT_TEMPLATE_PATH = TEMPLATE_DIR / 'default.html'

# デフォルトのCSSファイルパス
DEFAULT_CSS_PATH = CSS_DIR / 'default.css'

# デフォルトのテンプレート
DEFAULT_HTML_TEMPLATE = load_template_file(DEFAULT_TEMPLATE_PATH)

# デフォルトのCSS
DEFAULT_CSS = load_css_file(DEFAULT_CSS_PATH) 